from tkinter import *
win = Tk()
def addition():
    add_result = str(int(txt1.get()) + int(txt2.get()))
    lblResult.config(text="Sum:"), lblResult2.config(text=add_result)
def subtraction():
    sub_result = str(int(txt1.get()) - int(txt2.get()))
    lblResult.config(text="Difference:"), lblResult2.config(text=sub_result)
def multiply():
    mult_result = str(int(txt1.get()) * int(txt2.get()))
    lblResult.config(text="Product:"), lblResult2.config(text=mult_result)
def division():
    div_result = str(int(txt1.get()) / int(txt2.get()))
    lblResult.config(text="Quotient:"), lblResult2.config(text=div_result)
def floor_div():
    floor_div_result = str(int(txt1.get()) // int(txt2.get()))
    lblResult.config(text="Floor Quotient:"), lblResult2.config(text=floor_div_result)
def exponential():
    expo_result = str(int(txt1.get()) ** int(txt2.get()))
    lblResult.config(text="Power:"), lblResult2.config(text=expo_result)
def modulus():
    mod_result = str(int(txt1.get()) % int(txt2.get()))
    lblResult.config(text="Modulus:"), lblResult2.config(text=mod_result)
lblFNum = Label(win, text="First Number:", font=("Arial", 16))
lblFNum.place(x=5, y=20)
lblSNum = Label(win, text="Second Number:", font=("Arial", 16))
lblSNum.place(x=5, y=60)
lblResult = Label(win, text="Result:", font=("Arial", 16))
lblResult.place(x=5, y=100)
lblResult2 = Label(win, text="___", font=("Arial", 16))
lblResult2.place(x=200, y=95)
txt1 = Entry(win, width=25, font=("Arial", 16))
txt1.place(x=200, y=20)
txt2 = Entry(win, width=25, font=("Arial", 16))
txt2.place(x=200, y=60)
btnAdd = Button(win, width=3, text="+", font=("Arial", 16), command=addition)
btnAdd.place(x=60, y=150)
btnSub = Button(win, width=3, text="-", font=("Arial", 16), command=subtraction)
btnSub.place(x=120, y=150)
btnMult = Button(win, width=3, text="x", font=("Arial", 16), command=multiply)
btnMult.place(x=180, y=150)
btnDiv = Button(win, width=3, text="/", font=("Arial", 16), command=division)
btnDiv.place(x=240, y=150)
btnFloorDiv = Button(win, width=3, text="//", font=("Arial", 16), command=floor_div)
btnFloorDiv.place(x=300, y=150)
btnExpo = Button(win, width=3, text="^", font=("Arial", 16), command=exponential)
btnExpo.place(x=360, y=150)
btnMod = Button(win, width=3, text="%", font=("Arial", 16), command=modulus)
btnMod.place(x=420, y=150)
win.title("Domingo - Python GUI: Basic Calculator v1"), win.geometry("530x210+700+435")
win.config(bg="#996699")
win.mainloop()